// <auto-generated />
using System;
using AwawaTech.Mecanaut.API.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AwawaTech.Mecanaut.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709224954_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AwawaTech.Mecanaut.API.AssetManagement.Domain.Model.Aggregates.Machine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("machine_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("PlantId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.Property<long?>("ProductionLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("production_line_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("serial_number");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_machines");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_machines_serial_number");

                    b.ToTable("machines");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.AssetManagement.Domain.Model.Aggregates.Plant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_plants");

                    b.ToTable("plants");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.AssetManagement.Domain.Model.Aggregates.ProductionLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("production_line_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<long>("PlantId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_production_lines");

                    b.ToTable("production_lines");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.Competency.Domain.Model.Aggregates.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_skills");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("i_x_skills_name_tenant_id");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.ConditionMonitoring.Domain.Model.Aggregates.MachineMetrics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("machine_metrics_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("MachineId")
                        .HasColumnType("bigint")
                        .HasColumnName("machine_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_machine_metrics");

                    b.HasIndex("MachineId")
                        .IsUnique()
                        .HasDatabaseName("i_x_machine_metrics_machine_id");

                    b.ToTable("machine_metrics");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.ConditionMonitoring.Domain.Model.Aggregates.MetricDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("metric_definition_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_metric_definitions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_metric_definitions_name");

                    b.ToTable("metric_definitions");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.ConditionMonitoring.Domain.Model.Entities.MetricReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("metric_reading_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("MachineId")
                        .HasColumnType("bigint")
                        .HasColumnName("machine_id");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("measured_at");

                    b.Property<long>("MetricId")
                        .HasColumnType("bigint")
                        .HasColumnName("metric_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<double>("Value")
                        .HasColumnType("double")
                        .HasColumnName("value");

                    b.Property<long?>("machine_metrics_id")
                        .HasColumnType("bigint")
                        .HasColumnName("machine_metrics_id");

                    b.HasKey("Id")
                        .HasName("p_k_metric_readings");

                    b.HasIndex("machine_metrics_id")
                        .HasDatabaseName("i_x_metric_readings_machine_metrics_id");

                    b.HasIndex("MachineId", "MetricId", "MeasuredAt")
                        .HasDatabaseName("idx_machine_metric_time");

                    b.ToTable("metric_readings");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.DynamicMaintenancePlanning.Domain.Model.Aggregates.DynamicMaintenancePlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("dynamic_maintenance_plan_id");

                    b.Property<double>("Amount")
                        .HasColumnType("double")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("MetricId")
                        .HasColumnType("bigint")
                        .HasColumnName("metric_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<long>("PlantLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_line_id");

                    b.Property<long>("ProductionLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("production_line_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_dynamic_maintenance_plans");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("i_x_dynamic_maintenance_plans_name_tenant_id");

                    b.ToTable("dynamic_maintenance_plans");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.DynamicMaintenancePlanning.Domain.Model.Entities.DynamicMaintenancePlanMachine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("d_plan_machine_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("MachineId")
                        .HasColumnType("bigint")
                        .HasColumnName("machine_id");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_dynamic_maintenance_plan_machines");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("i_x_dynamic_maintenance_plan_machines_plan_id");

                    b.ToTable("dynamic_maintenance_plan_machines");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.DynamicMaintenancePlanning.Domain.Model.Entities.DynamicMaintenancePlanTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("d_plan_task_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("plan_id");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("task_description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_dynamic_maintenance_plan_tasks");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("i_x_dynamic_maintenance_plan_tasks_plan_id");

                    b.ToTable("dynamic_maintenance_plan_tasks");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.ExecutedWorkOrders.Domain.Model.Aggregates.ExecutedWorkOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Annotations")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("annotations");

                    b.Property<string>("AssignedTechnicianIds")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("assigned_technician_ids");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExecutedTasks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("executed_tasks");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("execution_date");

                    b.Property<string>("IntervenedMachineIds")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("intervened_machine_ids");

                    b.Property<long>("ProductionLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("production_line_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_executed_work_orders");

                    b.ToTable("executed_work_orders");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.ExecutedWorkOrders.Domain.Model.Entities.ExecutionImages", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("ExecutedWorkOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("executed_work_order_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_execution_images");

                    b.HasIndex("ExecutedWorkOrderId")
                        .HasDatabaseName("i_x_execution_images_executed_work_order_id");

                    b.ToTable("execution_images");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.ExecutedWorkOrders.Domain.Model.Entities.UsedProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("ExecutedWorkOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("executed_work_order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_used_products");

                    b.HasIndex("ExecutedWorkOrderId")
                        .HasDatabaseName("i_x_used_products_executed_work_order_id");

                    b.ToTable("used_products");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.IAM.Domain.Model.Aggregates.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<string>("CommercialName")
                        .HasColumnType("longtext")
                        .HasColumnName("commercial_name");

                    b.Property<string>("Country")
                        .HasColumnType("longtext")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("legal_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ruc");

                    b.Property<long>("SubscriptionPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("subscription_plan_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasColumnType("longtext")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("p_k_tenants");

                    b.ToTable("tenants");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.IAM.Domain.Model.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Name")
                        .HasColumnType("int")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_roles");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.InventoryManagement.Domain.Model.Aggregates.InventoryPart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_part_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int")
                        .HasColumnName("current_stock");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("int")
                        .HasColumnName("min_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("part_number");

                    b.Property<long>("PlantId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_inventory_parts");

                    b.HasIndex("PartNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_inventory_parts_part_number");

                    b.ToTable("inventory_parts");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.InventoryManagement.Domain.Model.Aggregates.PurchaseOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_order_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivery_date");

                    b.Property<long>("InventoryPartId")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_part_id");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("order_number");

                    b.Property<long>("PlantId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_purchase_orders");

                    b.ToTable("purchase_orders");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.Subscription.Domain.Model.Aggregates.SubscriptionPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("subscription_plan_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_subscription_plans");

                    b.ToTable("subscription_plans");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.TelemetryManagement.Domain.Model.Aggregates.ExperimentLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action_type");

                    b.Property<string>("AdditionalData")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("additional_data");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_milliseconds");

                    b.Property<string>("ExperimentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("experiment_name");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_success");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("variant");

                    b.HasKey("Id")
                        .HasName("p_k_experiment_logs");

                    b.ToTable("experiment_logs", (string)null);
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.WorkOrders.Domain.Model.Aggregates.WorkOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("work_order_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("MachineIds")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("machine_ids");

                    b.Property<long>("ProductionLineId")
                        .HasColumnType("bigint")
                        .HasColumnName("production_line_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Tasks")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tasks");

                    b.Property<string>("TechnicianIds")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("technician_ids");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_work_orders");

                    b.ToTable("work_orders");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int")
                        .HasColumnName("roles_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RolesId", "UserId")
                        .HasName("p_k_user_roles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_roles_user_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.AssetManagement.Domain.Model.Aggregates.Machine", b =>
                {
                    b.OwnsOne("AwawaTech.Mecanaut.API.AssetManagement.Domain.Model.ValueObjects.MachineSpecs", "Specs", b1 =>
                        {
                            b1.Property<long>("MachineId")
                                .HasColumnType("bigint")
                                .HasColumnName("machine_id");

                            b1.Property<string>("Manufacturer")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("manufacturer");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("model");

                            b1.Property<double>("PowerConsumption")
                                .HasColumnType("double")
                                .HasColumnName("power_consumption");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("type");

                            b1.HasKey("MachineId")
                                .HasName("p_k_machines");

                            b1.ToTable("machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId")
                                .HasConstraintName("f_k_machines_machines_machine_id");
                        });

                    b.OwnsOne("AwawaTech.Mecanaut.API.AssetManagement.Domain.Model.ValueObjects.MaintenanceInfo", "MaintenanceInfo", b1 =>
                        {
                            b1.Property<long>("MachineId")
                                .HasColumnType("bigint")
                                .HasColumnName("machine_id");

                            b1.Property<DateTime?>("LastMaintenance")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("last_maintenance");

                            b1.Property<DateTime?>("NextMaintenance")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("next_maintenance");

                            b1.HasKey("MachineId")
                                .HasName("p_k_machines");

                            b1.ToTable("machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId")
                                .HasConstraintName("f_k_machines_machines_machine_id");
                        });

                    b.Navigation("MaintenanceInfo")
                        .IsRequired();

                    b.Navigation("Specs")
                        .IsRequired();
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.AssetManagement.Domain.Model.Aggregates.Plant", b =>
                {
                    b.OwnsOne("AwawaTech.Mecanaut.API.AssetManagement.Domain.Model.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<long>("PlantId")
                                .HasColumnType("bigint")
                                .HasColumnName("plant_id");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("phone");

                            b1.HasKey("PlantId")
                                .HasName("p_k_plants");

                            b1.ToTable("plants");

                            b1.WithOwner()
                                .HasForeignKey("PlantId")
                                .HasConstraintName("f_k_plants_plants_plant_id");
                        });

                    b.OwnsOne("AwawaTech.Mecanaut.API.AssetManagement.Domain.Model.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<long>("PlantId")
                                .HasColumnType("bigint")
                                .HasColumnName("plant_id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("country");

                            b1.HasKey("PlantId")
                                .HasName("p_k_plants");

                            b1.ToTable("plants");

                            b1.WithOwner()
                                .HasForeignKey("PlantId")
                                .HasConstraintName("f_k_plants_plants_plant_id");
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.AssetManagement.Domain.Model.Aggregates.ProductionLine", b =>
                {
                    b.OwnsOne("AwawaTech.Mecanaut.API.AssetManagement.Domain.Model.ValueObjects.Capacity", "Capacity", b1 =>
                        {
                            b1.Property<long>("ProductionLineId")
                                .HasColumnType("bigint")
                                .HasColumnName("production_line_id");

                            b1.Property<double>("UnitsPerHour")
                                .HasColumnType("double")
                                .HasColumnName("units_per_hour");

                            b1.HasKey("ProductionLineId")
                                .HasName("p_k_production_lines");

                            b1.ToTable("production_lines");

                            b1.WithOwner()
                                .HasForeignKey("ProductionLineId")
                                .HasConstraintName("f_k_production_lines_production_lines_production_line_id");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.ConditionMonitoring.Domain.Model.Entities.MetricReading", b =>
                {
                    b.HasOne("AwawaTech.Mecanaut.API.ConditionMonitoring.Domain.Model.Aggregates.MachineMetrics", null)
                        .WithMany("Readings")
                        .HasForeignKey("machine_metrics_id")
                        .HasConstraintName("f_k_metric_readings_machine_metrics_machine_metrics_id");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.DynamicMaintenancePlanning.Domain.Model.Entities.DynamicMaintenancePlanMachine", b =>
                {
                    b.HasOne("AwawaTech.Mecanaut.API.DynamicMaintenancePlanning.Domain.Model.Aggregates.DynamicMaintenancePlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k__dynamic_maintenance_plan_machine__plan");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.DynamicMaintenancePlanning.Domain.Model.Entities.DynamicMaintenancePlanTask", b =>
                {
                    b.HasOne("AwawaTech.Mecanaut.API.DynamicMaintenancePlanning.Domain.Model.Aggregates.DynamicMaintenancePlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k__dynamic_maintenance_plan_task__plan");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.ExecutedWorkOrders.Domain.Model.Entities.ExecutionImages", b =>
                {
                    b.HasOne("AwawaTech.Mecanaut.API.ExecutedWorkOrders.Domain.Model.Aggregates.ExecutedWorkOrder", null)
                        .WithMany()
                        .HasForeignKey("ExecutedWorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_execution_images_executed_work_orders_executed_work_order_id");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.ExecutedWorkOrders.Domain.Model.Entities.UsedProduct", b =>
                {
                    b.HasOne("AwawaTech.Mecanaut.API.ExecutedWorkOrders.Domain.Model.Aggregates.ExecutedWorkOrder", null)
                        .WithMany()
                        .HasForeignKey("ExecutedWorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_used_products_executed_work_orders_executed_work_order_id");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.Subscription.Domain.Model.Aggregates.SubscriptionPlan", b =>
                {
                    b.OwnsOne("AwawaTech.Mecanaut.API.Subscription.Domain.Model.ValueObjects.SubscriptionFeatures", "Features", b1 =>
                        {
                            b1.Property<long>("SubscriptionPlanId")
                                .HasColumnType("bigint")
                                .HasColumnName("subscription_plan_id");

                            b1.Property<bool>("AdvancedAnalytics")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("advanced_analytics");

                            b1.Property<int>("MaxMachines")
                                .HasColumnType("int")
                                .HasColumnName("max_machines");

                            b1.Property<int>("MaxUsers")
                                .HasColumnType("int")
                                .HasColumnName("max_users");

                            b1.Property<bool>("PredictiveMaintenance")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("predictive_maintenance");

                            b1.Property<bool>("SupportPriority")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("support_priority");

                            b1.HasKey("SubscriptionPlanId")
                                .HasName("p_k_subscription_plans");

                            b1.ToTable("subscription_plans");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionPlanId")
                                .HasConstraintName("f_k_subscription_plans_subscription_plans_subscription_plan_id");
                        });

                    b.Navigation("Features")
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("AwawaTech.Mecanaut.API.IAM.Domain.Model.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_roles_roles_roles_id");

                    b.HasOne("AwawaTech.Mecanaut.API.IAM.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_roles_users_user_id");
                });

            modelBuilder.Entity("AwawaTech.Mecanaut.API.ConditionMonitoring.Domain.Model.Aggregates.MachineMetrics", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
